= 异常处理
:source-highlighter: highlight.js
:source-language: java
:toc: left
:toc-title: 异常处理
:toclevels: 3
:sectnums:

== 概述
=== 引言
- 在开发中，即使把代码写得尽善尽美，在系统的运行过程中仍然会遇到一些问题，因为很多问题不是靠代码能够避免的。 +
比如：客户输入数据的格式，读取文件是否存在，网络是否始终保持通畅等等。
- 通过过多的if-else分支来避免异常代码会导致程序的代码加长、臃肿，可读性差。因此采用异常处理机制，将异常处理的程序代码集中在一起，与正常的程序代码分开，使得程序简洁、优雅，并易于维护。

=== 定义
在Java语言中，将程序执行中发生的不正常情况称为“异常”。

NOTE: 开发过程中的语法错误和逻辑错误不是异常

== 错误(Error)
Java虚拟机无法解决的严重问题。如：JVM系统内部错误、资源耗尽等严重情况。比如：StackOverflowError和OOM。一般不编写针对性的代码进行处理。

.举例：栈溢出与堆溢出
----
public class ErrorTest {
	public static void main(String[] args) {
		//1.栈溢出：java.lang.StackOverflowError
//		main(args);
		//2.堆溢出：java.lang.OutOfMemoryError 
		Integer[] arr = new Integer[1024*1024*1024];
		
	}
}
----
== 异常(Exception)
其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。

== 分类
=== 运行时异常
- 是指编译器不要求强制处置的异常。一般是指编程时的逻辑错误，是程序员应该积极避免其出现的异常。java.lang.RuntimeException类及它的子类都是运行时异常。

=== 编译时异常
- 是指编译器要求必须处置的异常。即程序在运行时由于外界因素造成的一般性异常。编译器要求Java程序必须捕获或声明所有编译时异常。

=== 初步解决说明
- 一般有两种解决方法：
. 遇到错误就终止程序的运行。
. 由程序员在编写程序时，就考虑到错误的检测、错误消息的提示，以及错误的处理。

NOTE: 捕获错误最理想的是在编译期间，但有的错误只有在运行时才会发生。 +
比如：除数为0，数组下标越界等。

== 异常体系结构
image::images\\异常体系结构.png[]
== 常见异常
=== 编译时异常
.FileNotFoundException, IOException
[%collapsible]
====
----
//	@Test
//	public void test8() {
//		File file = new File("hello.txt");
		//FileNotFoundException
//		FileInputStream fis = new FileInputStream(file);<1>
//		//IOException
//		int data = fis.read();<2>
//		while(data != -1){
//			System.out.print((char)data);
			//IOException
//			data = fis.read();
//		}
//		//IOException
//		fis.close();
//	}
----
<1> FileNotFoundException
<2> IOException
====
=== 运行时异常
.NullPointerException（空指针异常）
[%collapsible]
====
----
@Test
public void test1(){
	int[] arr = null;
	System.out.println(arr[3]);
}
----
====
.ArrayIndexOutOfBoundsException（数组越界异常
[%collapsible]
====
----
@Test
public void test2() {
	int[] arr = new int[10];
	System.out.println(arr[10]);
}
----
====
.StringIndexOutOfBoundsException（字符串索引越界异常）
[%collapsible]
====
----
@Test
public void test3() {
	String str = "abc";
	System.out.println(str.charAt(3));
}
----
====
.ClassCastException（类转换异常）
[%collapsible]
====
----
@Test
public void test4() {
	Object obj = new Date();
	String str = (String)obj;
}
----
====
.NumberFormatException（数字格式异常）
[%collapsible]
====
----
@Test
public void test5() {
	String str = "123";
	str = "abc";
	int num = Integer.parseInt(str);
}
----
====
.InputMismatchException（输入不匹配异常）
[%collapsible]
====
----
@Test
public void test6() {
	Scanner scanner = new Scanner(System.in);
	int score = scanner.nextInt();//输入字符串"abc"
	System.out.println(score);
	
	scanner.close();
}
----
====
.ArithmeticException（算术异常）
[%collapsible]
====
----
@Test
public void test7() {
	int a = 10;
	int b = 0;
	System.out.println(a / b);
}
----
====
== 抓抛模型
- 过程一： +
**"抛"：**程序在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象。并将此对象抛出。一旦抛出对象以后，其后的代码就不再执行。 +
关于异常对象的产生：
** 系统自动生成的异常对象
** 手动的生成一个异常对象，并抛出（throw）
- 过程二： +
**"抓"：**可以理解为异常的处理方式：
** try-catch-finally
** throws

== 异常处理机制一：try-catch-finally
=== 格式
----
try{
// 可能出现异常的代码

}catch(异常类型1 变量名1)
{
	// 处理异常的方式1
}catch(异常类型2 变量名2)
{
	// 处理异常的方式2
}catch(异常类型3 变量名3)
{
	// 处理异常的方式3
}finally{
 		//一定会执行的代码
 }
----
NOTE: finally 是可选的。 +
catch也可省略，这是因为可能有运行时异常会自动执行。

=== 使用
==== 执行流程
. try将可能出现异常代码包装起来，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配。
. try中的异常对象匹配到某一个catch时，就进入catch中进行异常的处理。
. 一旦处理完成，若没有写finally，就跳出当前的try-catch结构，继续执行其后的代码。
. 若有finally，其中声明的是一定会被执行的代码。即使catch中又出现异常，try中有return语句，catch中有return语句等情况，finally中代码仍会执行。
+
NOTE: 像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动的回收的，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在finally中。

==== catch 中异常类型的顺序
- catch中的异常类型如果没有子父类关系，则无排序要求。
- catch中的异常类型如果满足子父类关系，则要求子类一定声明在父类的上面。否则会报错。

==== 常用的异常对象处理的方式
- String getMessage()
- printStackTrace()

==== 编译时异常与运行时异常的不同处理
.  使用try-catch-finally处理编译时异常，使得程序在编译时就不再报错，但是运行时仍可能报错。相当于我们使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现。
. 开发中，由于运行时异常比较常见，所以我们通常就不针对运行时异常编写try-catch-finally了。针对于编译时异常，一定要考虑异常的处理，将异常进行捕捉，转化为运行时异常。

==== 其他
.  在try结构中声明的变量，再出了try结构以后，就不能再被调用。
.  try-catch-finally结构可以嵌套。



== 异常处理的方式二：throws + 异常类型
=== 概述
- 如果一个方法(中的语句执行时)可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理。
- 在方法声明中用throws语句可以声明抛出异常的列表，throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类。

=== 格式
"throws + 异常类型"写在方法的声明处。指明此方法执行时，可能会抛出的异常类型。 +
`public static void method() throws FileNotFoundException,IOException{}`

=== 说明
- 一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，此对象满足throws后异常类型时，就会被抛出。异常代码后续的代码，就不再执行！
- try-catch-finally 真正的将异常给处理掉了。throws 的方式只是将异常抛给了方法的调用者。并没有真正将异常处理掉。

== 开发中如何选择使用try-catch-finally 还是使用throws？
- 如果父类中被重写的方法没有throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中有异常，必须使用try-catch-finally方式处理。
- 执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的。我们建议这几个方法使用throws的方式进行处理。而执行的方法a可以考虑使用try-catch-finally方式进行处理。

== 方法重写时的异常抛出规则
子类重写的方法抛出的异常类型不大于父类被重写的方法抛出的异常类型。意味着父类方法中有抛出异常时，子类重写方法可不抛出异常。

== [[手动抛出异常]]手动抛出异常
.例
----
public class ManualExceptionThrower {
	public static void main(String[] args) {
		try {
			Student stu = new Student();
			stu.regist(-1001);
			System.out.println(stu);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

class Student{
	private int id;
	
	public void regist(int id) throws Exception{
		if(id > 0) {
			this.id = id;
		}else {
			//手动抛出编译时异常
//			throw new Exception("您输入的数据非法！");<1>
			//手动抛出运行时异常
//			throw new RuntimeException("您输入的数据非法！");<2>
			//抛出自定义负数异常
			throw new NegativeException("您输入的数据非法！");<3>
		}
	}

	@Override
	public String toString() {
		return "sutdent [id=" + id + "]";
	}
	
}
----
<1> 手动抛出编译时异常
<2> 手动抛出运行时异常
<3> 抛出自定义负数异常

== 用户自定义异常类
一般地，用户自定义异常类都是RuntimeException的子类。
. 自定义异常类通常需要编写几个重载的构造器。
. 自定义异常需要提供serialVersionUID
. 自定义的异常通过throw抛出。
. 自定义异常最重要的是异常类的名字，当异常出现时，可以根据名字判断异常类型。

.例
----
//自定义异常
public class NegativeException extends Exception {

	private static final long serialVersionUID = -5596452560685957455L;
	
	public NegativeException() {
		
	}
	public NegativeException(String msg) {
		super(msg);
	}
}
----
该异常的测试见<<手动抛出异常>>。